# Generated by Django 6.0.3 on 2026-03-11 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_name'),
        ('projects', '0009_alter_task_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('project_created', 'created project'), ('project_updated', 'updated project'), ('project_deleted', 'deleted project'), ('task_created', 'created task'), ('task_updated', 'updated task'), ('task_deleted', 'deleted task'), ('task_completed', 'completed task'), ('task_reopened', 'reopened task'), ('member_invited', 'invited member'), ('member_joined', 'joined organisation'), ('member_removed', 'removed member'), ('role_changed', 'changed role')], db_index=True, max_length=30)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='projects.project')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organisation', '-created_at'], name='projects_ac_organis_c77b8b_idx'), models.Index(fields=['project', '-created_at'], name='projects_ac_project_9cc7b7_idx')],
            },
        ),
    ]
