# Generated by Django 6.0.3 on 2026-03-12 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='verb',
            field=models.CharField(choices=[('project_created', 'created project'), ('project_updated', 'updated project'), ('project_deleted', 'deleted project'), ('task_created', 'created task'), ('task_updated', 'updated task'), ('task_deleted', 'deleted task'), ('task_completed', 'completed task'), ('task_reopened', 'reopened task'), ('member_invited', 'invited member'), ('member_joined', 'joined organisation'), ('member_removed', 'removed member'), ('role_changed', 'changed role'), ('attachment_added', 'attached file'), ('attachment_removed', 'removed attachment')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudinary_public_id', models.CharField(max_length=500)),
                ('cloudinary_url', models.CharField(max_length=1000)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.task')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Attachment',
                'verbose_name_plural': 'Task Attachments',
                'ordering': ['created_at'],
            },
        ),
    ]
