# Generated by Django 6.0.3 on 2026-03-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_activitylog_verb_taskattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image_public_id',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_image_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
