# Generated by Django 6.0.3 on 2026-03-12 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_name'),
        ('projects', '0012_project_cover_image_public_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activitylog',
            name='projects_ac_organis_c77b8b_idx',
        ),
        migrations.RenameField(
            model_name='activitylog',
            old_name='organisation',
            new_name='organization',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='verb',
            field=models.CharField(choices=[('project_created', 'created project'), ('project_updated', 'updated project'), ('project_deleted', 'deleted project'), ('task_created', 'created task'), ('task_updated', 'updated task'), ('task_deleted', 'deleted task'), ('task_completed', 'completed task'), ('task_reopened', 'reopened task'), ('member_invited', 'invited member'), ('member_joined', 'joined organization'), ('member_removed', 'removed member'), ('role_changed', 'changed role'), ('attachment_added', 'attached file'), ('attachment_removed', 'removed attachment')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['organization', '-created_at'], name='projects_ac_organiz_21dec4_idx'),
        ),
    ]
