# Generated by Django 6.0.3 on 2026-03-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_projectguestinvite_projectmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='verb',
            field=models.CharField(choices=[('project_created', 'created project'), ('project_updated', 'updated project'), ('project_deleted', 'deleted project'), ('task_created', 'created task'), ('task_updated', 'updated task'), ('task_deleted', 'deleted task'), ('task_completed', 'completed task'), ('task_reopened', 'reopened task'), ('member_invited', 'invited member'), ('member_joined', 'joined organization'), ('member_removed', 'removed member'), ('member_left', 'left'), ('role_changed', 'changed role'), ('attachment_added', 'attached file'), ('attachment_removed', 'removed attachment')], db_index=True, max_length=30),
        ),
    ]
