# Generated by Django 6.0.3 on 2026-03-26 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_project_name_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
