# Generated by Django 6.0.3 on 2026-03-31 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_activitylog_verb_taskcomment_chatmessage'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='projects_ch_project_168484_idx',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
