# Generated by Codex on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_remove_chatmessage_projects_ch_project_168484_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
