# Generated by Django 6.0.3 on 2026-03-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('org_invite', 'Organization Invite'), ('join_request', 'Join Request'), ('invite_accepted', 'Invite Accepted'), ('invite_rejected', 'Invite Rejected'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('task_assigned', 'Task Assigned'), ('project_guest_invite', 'Project Guest Invite')], max_length=20),
        ),
    ]
