# Generated by Django 6.0.3 on 2026-03-22 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_notification_type'),
        ('projects', '0017_alter_project_name_alter_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='project_guest_invite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.projectguestinvite'),
        ),
    ]
