# Generated by Django 6.0.3 on 2026-04-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_notification_project_guest_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
