# Generated by Django 6.0.3 on 2026-04-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_organization_logo_public_id_organization_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='logo_public_id',
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
