# Generated by Django 6.0.3 on 2026-03-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_avatar_url_userprofile_google_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='digest_frequency',
            field=models.CharField(choices=[('daily', 'Daily (urgent tasks only)'), ('weekly', 'Weekly summary'), ('never', 'Never')], default='weekly', max_length=10),
        ),
    ]
